### ISSUE TITLE
make dropdowns

### ISSUE THREAD

**Issue by chellanivaibhav** [anonymous043044/startup-bvp#16]
@bansaltush please make me dropdowns named by 
1. distance from college (options 1km -3 km , 3m -5km )
2. budget (options different budget ranges)
3. gender (oprions male female)
 
so that i can link them with databases 
URGENT

**Comment by bansaltush** [comment]
give me half hour /. ,,  some changes are needed

**Comment by bansaltush** [comment]
done . i will center them and then i will push ,, tell me what other things u  need urgent ,, or will require inn future ,

**Comment by bansaltush** [comment]
give me a call when u need things urgent

**Comment by vaibhavchellani** [comment]
okay bhai

**Comment by bansaltush** [comment]
merge kr liyo bhai ,,mene push kiye the kl

**Comment by chellanivaibhav** [comment]
kahan hai bhai PR

**Comment by chellanivaibhav** [comment]
kahan hai bhai PR

**Comment by chellanivaibhav** [comment]
tereko push karne ke baad yahan pe PR bhi create karni thi

**Comment by bansaltush** [comment]
ab kr liya na ?

**Comment by bansaltush** [comment]
close this .. it is done.. i think
